<?php

namespace app\admin\controller;

use think\Controller;
use think\Exception;
use think\Request;

class Goods extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkJWT();
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
//        try {
        $model = model('Goodsmodel');

        $data = $this->request->get();

        if (isset($data['page']) && !empty($data['page'])) {
            $page = $data['page'];
        } else {
            $page = 1;
        }
        if (isset($data['limit']) && !empty($data['limit'])) {
            $limit = $data['limit'];
        } else {
            $limit = 3;
        }

        $sarr = [];

        if (!empty($data['gname'])) {
            $sarr['gname'] = ['like', '%' . $data['gname'] . '%'];
        }
        if (!empty($data['gename'])) {
            $sarr['gename'] = ['like', '%' . $data['gename'] . '%'];
        }
        if (!empty($data['lowprice']) && !empty($data['highprice']) && $data['lowprice'] < $data['highprice']) {
            $sarr['price'] = [
                    ['>',$data['lowprice']],
                    ['<',$data['highprice']]
            ];
        }
        if($data['typeid']){
            $sarr['cid'] = $data['typeid'];
        }


        $goods = $model->querys($sarr,$page, $limit);

//        echo $model->getLastSql();
        $total = $goods->total();
        $data = $goods->items();

        if ($total) {
            return json([
                'code' => config('code.success'),
                'msg' => '商品获取成功',
                'data' => $data,
                'total' => $total
            ]);
        } else {
            return json([
                'code' => config('code.success'),
                'msg' => '暂无商品',
                'data' => []
            ]);
        }
//        }catch (Exception $exception){
//            return json([
//                'code' => config('code.fail'),
//                'msg' => '商品获取失败'
//            ]);
//        }
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param \think\Request $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        //
        $data = $this->request->post();
        $model = model('Goodsmodel');
        $result = $model->inserts($data);
        if ($result) {
            return json([
                'code' => config('code.success'),
                'msg' => '商品添加成功'
            ]);
        } else {
            return json([
                'code' => config('code.fail'),
                'msg' => '商品添加失败'
            ]);
        }
    }

    /**
     * 显示指定的资源
     *
     * @param int $id
     * @return \think\Response
     */
    public function read($id)
    {
        $model = model('Goodsmodel');
        $result = $model->queryone(['gid'=>$id]);

        if($result){
            return  json([
               'code'=>config('code.success'),
               'msg'=>"商品获取成功",
               'data'=>$result
            ]);
        }else{
            return  json([
                'code'=>config('code.success'),
                'msg'=>"暂无商品"
            ]);
        }


    }

    /**
     * 显示编辑资源表单页.
     *
     * @param int $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param \think\Request $request
     * @param int $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param int $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
