<?php

namespace app\index\controller;

use think\Controller;
use think\Db;
use think\Request;

class Shopcart extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkJWT();
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        //
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        $data = $this->request->post();
        $uid = $this->request->id;

        $cart = Db::table('cart')->where('uid',$uid)->find();
        // 存在购物车  uid->cart表

        if($cart){
            // 存在
        }else{
            // 不存在 -> 初始化 cart (uid,total:1,price:) -> 添加商品 cart_extra(gid,num:1,state:1,sid:,uid)
            Db::startTrans();
            $cartInfo = ['uid'=>$uid,'total'=>1,'price'=>$data['price']];
             Db::table('cart')->insert($cartInfo);
            $sid = Db::table('cart')->insertGetId($cartInfo);
            $cartExtra = ['gid'=>$data['gid'],'num'=>1,'state'=>1,'uid'=>$uid,'sid'=>$sid];
            $result = Db::table('cart_extra')->insert($cartExtra);
            if($sid && $result){
                Db::commit();
            }else{
                Db::rollback();
            }
        }


    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
